Numpy arrays and basics

In [2]:
import numpy as np

### creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("arr_1d:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("arr_2d:", arr_2d)

arr_1d: [1 2 3 4 5]
arr_2d: [[1 2 3]
 [4 5 6]]


### list vs numpy arrays

In [ ]:
py_list = [1,2,3]
print("python list multiplication: ", py_list*2)

np_array = np.array(py_list)
print("numpy array multiplication: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time:", time.time()-start)


start = time.time()
py_list = np.arange(1000000)*2 #this function let's us creaet a array upto this point
print("\n list operation time:", time.time()-start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]

 list operation time: 0.15808796882629395

 list operation time: 0.02344059944152832


### Creating arrays from scratch

In [15]:
zeroes = np.zeros((3,4))
print("zeroes arrays: \n", zeroes)

ones = np.ones((3,4))
print("\n ones arrays: \n", ones)

zeroes arrays: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones arrays: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)

full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.45037634 0.84607184 0.51366303]
 [0.78662553 0.49071383 0.06592727]]
sequence array: 
 [0 2 4 6 8]


### vector,matrices and tensor

In [6]:
vector = np.array([1,2,3])
print("vector :\n", vector )

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix : \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: \n",tensor)

vector :
 [1 2 3]
matrix : 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Arrays properties

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape: ",arr.shape)
print("dimension", arr.ndim)
print("size", arr.size)
print("Dtype:",arr.dtype)

shape:  (2, 3)
dimension 2
size 6
Dtype: int64


### Array Reshaping

In [21]:
arr = np.arange(12)
print("original array",arr)

reshaped = arr.reshape((3,4))
print("reshaped array: \n",reshaped)

# returns view instead of copy
raveled = reshaped.ravel()
print("revled: \n",raveled)

#transpose
transpose = reshaped.T
print("transposed array: \n",transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
revled: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
