## Numpy Array operation

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])
print("basic slicing: ",arr[1:7])
print("with step: ",arr[1:8:2])
print("Negative indexing", arr[-3])

basic slicing:  [2 3 4 5 6 7]
with step:  [2 4 6 8]
Negative indexing 6


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [6,7,8]])
print("specific element: ",arr_2d[1,2])
print("Entire row: ",arr_2d[1])
print("Entire col: ",arr_2d[:,1])

specific element:  6
Entire row:  [4 5 6]
Entire col:  [2 5 7]


## Sorting

In [6]:
unsorted = np.array([3,2,5,6,1,2,3])
print("sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("sorted array: \n",np.sort(arr_2d_unsorted, axis = 0))
print("sorted array: \n",np.sort(arr_2d_unsorted, axis = 1))

sorted array:  [1 2 2 3 3 5 6]
sorted array: 
 [[1 1]
 [2 2]
 [3 3]]
sorted array: 
 [[1 3]
 [1 2]
 [2 3]]


## Filters

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
Even_numbers = numbers[numbers%2==0]
print("Even No.: ",Even_numbers)

Even No.:  [ 2  4  6  8 10]


## filter with mask

In [8]:
mask = numbers>5
print("number greater than 5: ",numbers[mask])

number greater than 5:  [ 6  7  8  9 10]


## Fance indexing vs np.where()

In [10]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("Np where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [12]:
condition_array = np.where(numbers>5,numbers*2,numbers)
print("condition_array: ",condition_array)

condition_array = np.where(numbers>5,True,False)
print("condition_array: ",condition_array)

condition_array:  [ 1  2  3  4  5 12 14 16 18 20]
condition_array:  [False False False False False  True  True  True  True  True]


## Adding and removing the data

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatiblity

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6,6])
c = np.array([7,8,9])

print("compatiblity_shape:", a.shape == b.shape)

compatiblity_shape: False


In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n with_new_row: \n",with_new_row)
#vstack adds a row

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("\n with_new_col: \n",with_new_col)
#hstack adds a column

[[1 2]
 [3 4]]

 with_new_row: 
 [[1 2]
 [3 4]
 [5 6]]

 with_new_col: 
 [[1 2 7]
 [3 4 8]]


In [26]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr,2)
print("array after deletion: ",deleted)

array after deletion:  [1 2 4 5 6 7]
